services:
  mssql:
    container_name: mssql
    build:
      context: docker
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - ./docker/data:/var/opt/mssql/data