USE storage;
GO
DROP PROCEDURE IF EXISTS dbo.Login;
GO
CREATE PROCEDURE dbo.Login
@USERNAME_EMAIL VARCHAR(255)
AS
BEGIN
    SELECT id, password FROM dbo.users WHERE username_email=@USERNAME_EMAIL;
END