USE storage;
GO
DROP PROCEDURE IF EXISTS dbo.AddAccount;
GO
CREATE PROCEDURE dbo.AddAccount
@ID INT,
@NAME VARCHAR(255),
@URL VARCHAR(255),
@FAVICON VARCHAR(MAX),
@ACCOUNT VARCHAR(255),
@PASSWORD VARCHAR(255)
AS
BEGIN
    INSERT INTO dbo.accounts (user_id, name, url, favicon, account, password)
    VALUES (@ID, @NAME, @URL, @FAVICON, @ACCOUNT, @PASSWORD)
END