DROP PROCEDURE IF EXISTS AddProfile;
GO
CREATE PROCEDURE AddProfile
@EMAIL VARCHAR(255),
@PASSWORD VARCHAR(255)
AS
BEGIN
    INSERT INTO users (username_email, password)
    VALUES (@EMAIL ,@PASSWORD)
END