USE storage;
GO
DROP PROCEDURE IF EXISTS dbo.AddProfile;
GO
CREATE PROCEDURE dbo.AddProfile
@EMAIL VARCHAR(255),
@PASSWORD VARCHAR(255)
AS
BEGIN
    INSERT INTO dbo.users (username_email, password)
    VALUES (@EMAIL ,@PASSWORD)
END